# Generated by Django 2.2.1 on 2019-06-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='querymanager.Programmer'),
        ),
    ]
