# Generated by Django 2.2.1 on 2019-06-29 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0002_auto_20190627_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
    ]
