# Generated by Django 2.2.1 on 2019-07-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='tags',
            field=models.ManyToManyField(to='querymanager.Tag'),
        ),
    ]
