# Generated by Django 2.2.1 on 2019-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0004_query_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='tags',
            field=models.ManyToManyField(blank=True, to='querymanager.Tag'),
        ),
    ]
