# Generated by Django 2.2.1 on 2019-07-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querymanager', '0005_auto_20190706_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['query_id'], 'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_name']},
        ),
        migrations.AddField(
            model_name='programmer',
            name='title',
            field=models.CharField(default='IT Manager', max_length=100),
            preserve_default=False,
        ),
    ]
